networks:
  thpsrun:
    name: thpsrun
    external: true

services:
  react:
    container_name: react
    restart: unless-stopped
    ports:
      - "8081:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY}
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    tty: true
    volumes:
      - ./frontend:/srv/app:rw
      - node_modules:/srv/app/node_modules:rw
    networks:
      - thpsrun
