networks:
  thpsrun:
    name: thpsrun
    external: true

services:
  react:
    container_name: react
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    security_opt:
      - no-new-privileges:true
    networks:
      - thpsrun
